repositoryUrl: git@github.com:InOG-projects/IRIS-library-js.git
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - '@semantic-release/git'
