language: node_js
node_js:
  - '12.14.1'
jobs:
  include:
    - stage: test
      script: yarn test
      after_success:
        - yarn codecov
    - stage: publish
      if: branch = master
      script: semantic-release
      before_install:
        - openssl aes-256-cbc -K $encrypted_7d58c9ef7168_key -iv $encrypted_7d58c9ef7168_iv -in git_deploy_key.enc -out /tmp/git_deploy_key -d
        - chmod 600 /tmp/git_deploy_key
        - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
        - eval "$(ssh-agent -s)"
        - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
notifications:
  email:
    recipients:
      - me@silverxu.com
    on_success: always
    on_failure: always
